[package]
name="shared"
version = "0.1.0"
edition.workspace = true

[dependencies]
tokio-vsock = {workspace = true}
serde = {workspace = true}
serde_cbor = {workspace = true}
tokio = {workspace = true}
thiserror = {workspace = true}
